import { color } from "@mui/system";

export const activityType = [
  { value: "Athletics", label: "Athletics" },
  { value: "Badminton", label: "Badminton" },
  { value: "Basketball", label: "Basketball" },
  { value: "Cricket", label: "Cricket" },
  { value: "Cycling", label: "Cycling" },
  { value: "Football", label: "Football" },
  { value: "Gaelic", label: "Gaelic" },
  { value: "Gym", label: "Gym" },
  { value: "Golf", label: "Golf" },
  { value: "Gymnastics", label: "Gymnastics" },
  { value: "Hiking", label: "Hiking" },
  { value: "MMA", label: "MMA" },
  { value: "Netball", label: "Netball" },
  { value: "Other", label: "Other" },
  { value: "Rugby", label: "Rugby" },
  { value: "Running", label: "Running" },
  { value: "Table Tennis", label: "Table Tennis" },
  { value: "Tennis", label: "Tennis" },
  { value: "Volleyball", label: "Volleyball" },
  { value: "Walking", label: "Walking" },
  { value: "Water Sports", label: "Water Sports" },
];

export const gender = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Mixed", label: "Mixed" },
];

export const price = [
  { value: "0", label: "£0" },
  { value: "1", label: "£1" },
  { value: "2", label: "£2" },
  { value: "3", label: "£3" },
  { value: "4", label: "£4" },
  { value: "5", label: "£5" },
  { value: "6", label: "£6" },
  { value: "7", label: "£7" },
  { value: "8", label: "£8" },
  { value: "9", label: "£9" },
  { value: "10", label: "£10" },
  { value: "10<", label: "£10<" },
];

export const maxCapacity = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
  { value: "6", label: "6" },
  { value: "7", label: "7" },
  { value: "8", label: "8" },
  { value: "9", label: "9" },
  { value: "10", label: "10" },
  { value: "11", label: "11" },
  { value: "12", label: "12" },
  { value: "13", label: "13" },
  { value: "14", label: "14" },
  { value: "15", label: "15" },
  { value: "16", label: "16" },
  { value: "17", label: "17" },
  { value: "18", label: "18" },
  { value: "19", label: "19" },
  { value: "20", label: "20" },
  { value: "21", label: "21" },
  { value: "22", label: "22" },
  { value: "23", label: "23" },
  { value: "24", label: "24" },
  { value: "25", label: "25" },
  { value: "26", label: "26" },
  { value: "27", label: "27" },
  { value: "28", label: "28" },
  { value: "29", label: "29" },
  { value: "30", label: "30" },
];
